services:
  pocketbase:
    container_name: pocketbase
    build:
      context: .
      dockerfile: Dockerfile.pocketbase
    ports:
      - 8090:8090
    volumes:
      - ./pb/data:/pb/pb_data
    restart: no
  bot:
    depends_on:
      pocketbase:
        condition: service_started
    container_name: dogbot
    build:
      context: .
      dockerfile: Dockerfile.dogbot
    restart: no
    develop:
      watch:
        - action: rebuild
          path: ./src
    environment:
      - CLIENT_ID=$CLIENT_ID
      - CLIENT_SECRET=$CLIENT_SECRET
      - OAUTH_CODE=$OAUTH_CODE
