services:
  valkey:
    image: valkey/valkey:alpine
    container_name: qweribot-valkey
    ports:
      - 6379:6379
    restart: no
    volumes:
      - ./db/redis:/data
    environment:
      - VALKEY_EXTRA_FLAGS=--save 60 1
  postgres:
    container_name: qweribot-postgres
    image: postgres:latest
    restart: unless-stopped
    env_file: 
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgresql:/var/lib/postgresql/data
