services:
  pocketbase:
    container_name: pocketbase
    build:
      context: .
      dockerfile: Dockerfile.pocketbase
    ports:
      - 8090:8090
    volumes:
      - ./pb:/pb/pb_data
    restart: no
  bot:
    container_name: dogbot
    build:
      context: .
      dockerfile: Dockerfile.dogbot
    restart: no
    develop:
      watch:
        - action: rebuild
          path: ./src
