name: Build and Publish docker image

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to container Registry
        uses: docker/login-action@v3
        with:
          registry: git.qwerinope.com
          username: qwerinope
          password: ${{ secrets.PAT }}
      - name: Get repository
        uses: actions/checkout@v4
      - name: Docker Build and push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.dogbot
          context: .
          push: true
          tags: git.qwerinope.com/dogbot:latest
